require("core.plugin_config.Comment")
require("core.plugin_config.cmp")
require("core.plugin_config.gitsigns")
require("core.plugin_config.indent_blankline")
require("core.plugin_config.lsp")
require("core.plugin_config.lualine")
require("core.plugin_config.telescope")
require("core.plugin_config.treesitter")
require("core.plugin_config.which-key")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.navigator")
require("core.plugin_config.nvim-autopairs")
require("core.plugin_config.vim-system-copy")
require("core.plugin_config.neoscroll")
--require("core.plugin_config.null-ls")
require("core.plugin_config.prettier")
require("core.plugin_config.chatgpt")

-- colorscheme
--require("core.plugin_config.gruvbox")
require("core.plugin_config.onedark")
